### PR TITLE
Nana/docker

### PR DESCRIPTION
**Pull request by ghost**
Hello there!

First of all and most importantly, thank you for your hard work. I've heard the news about brainlets.moe going offline, so as a first measure, I wanted to make it easier for people to self-host the project by providing build and deploy instructions for creating dockerized versions of it.

### CODE REVIEW

**Comment by umang-p** [comment]
Thank you. Anything that can make development easier is appreciated. Using django was a dumb decision for a project this simple.

As I don't (yet) know much about Docker, I'll have to trust that this works and youve tested it.

**Comment by MadManMork** [comment]
> Hello there!
> 
> First of all and most importantly, thank you for your hard work. I've heard the news about brainlets.moe going offline, so as a first measure, I wanted to make it easier for people to self-host the project by providing build and deploy instructions for creating dockerized versions of it.

Hi, sorry to bother @nananamae but I was wondering if you would mind putting together some sort of instructional document so that people that aren't so versed in all these odds and ends can self-host the project as a utility? It would help out a lot of people that regularly visit the existing tool once it goes offline for good, as well as make it even easier for those who want to help out with post-website upkeep to do so.
As it happens, I'm fiddling with a less complicated project myself at the moment, so being able to get this working on my local machine would be a godsend for salvaging the maths behind some of the calculations.

**Comment by ghost** [comment]
@MadManMork Sure thing, it's not bothering me at all - I originally meant to add instructions after I've figured out how to properly maintain project data (like doll/eq/fairy stats), but if I'm not mistaken, the process of adding a new doll to the system is terribly complex. I haven't found any information regarding data structures or the simulation model either, so as much as I dislike reinventing wheels, I'm at a loss how to proceed with the current implementation.

**Comment by umang-p** [comment]
@nananamae It may be worth looking through commit history to see how some of the simpler dolls were added. For dolls who have a skill that is just a simple stat buff, adding them is actually very easy. See dd3e5a95e5da2b751a5a63704c3a1baa37e74d99 as an example, no changes to the code required. The mess comes from all the dolls with complicated skills.

I know that there is no documentation (I never planned on making the sim when i first started this project and it turned out to be a bad idea) and if I can find some time before May, I'd rather first spend it trying to get rid of django. I'll still be around to answer any questions.

**Pull request merged**
